### PR TITLE
final pull

### PR DESCRIPTION
**Pull request by Alexandre-Kononov**
Final pull before the project is finalized

### CODE REVIEW

**Comment by Alexandre-Kononov** [comment]
conflict

**Comment by Alexandre-Kononov** [comment]
condlict

**Comment by MikMar99** [comment]
So here you want to merge the main branch into your branch? the way i normally do it is to merge the main from remote to local and then merge the local main onto local personal branch.

But happy to merge this like this if you confirm that is what you want.

**Comment by MikMar99** [comment]
Cancelling this as requested

**Pull request closed without merging**
